### ISSUE TITLE
点击hierarchy

### ISSUE THREAD

**Issue by Jack-simo** [whataa/pandora#17]
Process: com.yonghui.vender.datacenter, PID: 20302
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yonghui.vender.datacenter/tech.linjiang.pandora.ui.Dispatcher}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at tech.linjiang.pandora.inspector.treenode.ViewNode.<init>(ViewNode.java:44)
        at tech.linjiang.pandora.inspector.treenode.ViewNode.create(ViewNode.java:50)
        at tech.linjiang.pandora.inspector.treenode.TreeView.setRootView(TreeView.java:103)
        at tech.linjiang.pandora.ui.fragment.ViewFragment.getLayoutView(ViewFragment.java:57)
        at tech.linjiang.pandora.ui.fragment.BaseFragment.onCreateView(BaseFragment.java:94)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
        at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1254)
        at android.app.Activity.performStart(Activity.java:6930)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2756)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by whataa** [comment]
1. 请问在你那里是必现的吗？
2. 是否有发生内存回收或者屏幕旋转之类的操作？

**Comment by whataa** [comment]
Close because of no response
