### ISSUE TITLE
Android 9.0 can not open activity

### ISSUE THREAD

**Issue by xuhaoyang** [whataa/pandora#24]
device: Google Pixel2
system: Android 9 

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.echatsoft.nativesdkdemo, PID: 17203
    android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at android.app.ContextImpl.startActivity(ContextImpl.java:912)
        at android.app.ContextImpl.startActivity(ContextImpl.java:888)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
        at tech.linjiang.pandora.ui.Dispatcher.start(Dispatcher.java:41)
        at tech.linjiang.pandora.ui.connector.OnEntranceClick.onClick(OnEntranceClick.java:37)
        at tech.linjiang.pandora.Pandora$2.onClick(Pandora.java:69)
        at tech.linjiang.pandora.ui.connector.OnEntranceClick.onClick(OnEntranceClick.java:21)
        at tech.linjiang.pandora.ui.view.EntranceView.onClick(EntranceView.java:189)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by whataa** [comment]
It seems that the version you are using is not up to date. Can you try it with the latest version ?
 `v1.1.3`

**Comment by xuhaoyang** [comment]
i have used the latest version @whataa

**Comment by whataa** [comment]
This flag is very ridiculous in different android versions, just like a bug, please check out a newer version.  `v1.1.4`

**Comment by xuhaoyang** [comment]
1.1.4 to work now
