### ISSUE TITLE
java.lang.IllegalStateException: Pandora.get() must not be null

### ISSUE THREAD

**Issue by joker-fu** [whataa/pandora#29]
在application中 设置 okhttp的interceptor时报错

**Comment by whataa** [comment]
请问是哪个版本，贴上堆栈看看呢

**Comment by joker-fu** [comment]
之前不是1.2.0，换成1.2.0也是一样的

 Process: com.****.****.debug:leakcanary, PID: 5852
    java.lang.RuntimeException: Unable to create application com.****.****.GoApplication: java.lang.IllegalStateException: Pandora.get() must not be null
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4794)
        at android.app.ActivityThread.access$1700(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5567)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:742)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)
     Caused by: java.lang.IllegalStateException: Pandora.get() must not be null
        at com.****.common.CommonApplication.initAppConfigures(CommonApplication.kt:34)
        at com.****.common.CommonApplication.onCreate(CommonApplication.kt:24)
        at com.****.****.GoApplication.onCreate(GoApplication.kt:36)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4791)
        at android.app.ActivityThread.access$1700(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5567) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:742) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)

**Comment by joker-fu** [comment]
正常运行下桌面上都不会创建出leasks图标（之前项目运行的时候报Pandora.get() must not be null没太在在意，最近leakcanary报内存泄露，光看见弹出，但是act没有，才发现是这个问题导致），使用LeakCanary.enableDisplayLeakActivity(this)桌面上创建出leaks，但是点击报错

**Comment by whataa** [comment]
因为 leakcanary 开辟了自己的进程，而 Pandora 是在 Provider 里面初始化的，Provider 默认只会在主进程中初始化，所以当 leakcanary 进程启动的时候，初始化了Application，但是 Pandora 并没有初始化，结果就导致调用 `Pandora.get().xxx` 的地方都会空指针。

我看了下 leakcanary 的[文档](https://github.com/square/leakcanary)，其初始化的代码如下：
```
public class ExampleApplication extends Application {

  @Override public void onCreate() {
    super.onCreate();
    if (LeakCanary.isInAnalyzerProcess(this)) {
      // This process is dedicated to LeakCanary for heap analysis.
      // You should not init your app in this process.
      return;
    }
    LeakCanary.install(this);
    // Normal app init code...
  }
}
```
也就是说，如果当前是 leakcanary 进程，就不执行其后面的代码，这其中就包括Pandora的相关调用。

最后我建议的是仅在主进程使用Pandora，对Pandora相关进行配置时判断一下进程。
