### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by JesseWo** [whataa/pandora#31]
机型：魅族M5s
Android版本：6.0
报错堆栈信息：
``` 
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.action.MANAGE_OVERLAY_PERMISSION dat=package:xxxxxx
flg=0x10000000 }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1835)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1549)
        at android.app.ContextImpl.startActivity(ContextImpl.java:705)
        at android.app.ContextImpl.startActivity(ContextImpl.java:687)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
        at tech.linjiang.pandora.util.Utils.checkPermission(Utils.java:150)
        at tech.linjiang.pandora.Pandora.open(Pandora.java:91)
        ....
```

**Comment by whataa** [comment]
看来似乎是魅族的魔改操作把这个Activity移除掉了。  
由于该库的主要特性并不包含对权限的适配，所以我打算仅catch住该crash，提示开发者自行到对应页面进行授权。  
感谢你的反馈。
