### ISSUE TITLE
Pandora.get().getBottomActivity() 为空

### ISSUE THREAD

**Issue by Thewhitelight** [whataa/pandora#41]
点击 Select 崩溃

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.janmart.dms.devs/tech.linjiang.pandora.ui.TransActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2489)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2551)
        at android.app.ActivityThread.access$1000(ActivityThread.java:169)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1432)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5581)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)
     **Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
        at tech.linjiang.pandora.util.ViewKnife.tryGetTheFrontView(ViewKnife.java:259)
        at tech.linjiang.pandora.inspector.ElementHoldView.tryGetFrontView(ElementHoldView.java:103)
        at tech.linjiang.pandora.ui.fragment.ViewFragment.getLayoutView(ViewFragment.java:52)
        at tech.linjiang.pandora.ui.fragment.BaseFragment.onCreateView(BaseFragment.java:108)**
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)

[1.3.2版本]Pandora.get().getBottomActivity() 拿到的 activity 为空

**Comment by whataa** [comment]
这里的逻辑对状态回收的情况处理有点问题，请先试试dev分支的最新版本：917ca7a754（即把v1.3.2改为917ca7a754），开发基本完毕但是还没发布。

**Comment by whataa** [comment]
已发布为v2.0.0
