### ISSUE TITLE
新建BuildTypes的时候，启动黑屏。

### ISSUE THREAD

**Issue by Dramadream** [whataa/pandora#43]
buildTpyes中多加了一个类型debugTest，使用这个运行就会出问题。
gradle中的配置如下：

    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            zipAlignEnabled true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            // 是否处于调试状态
            buildConfigField("boolean", "IS_DEBUGING", "false")
            // 服务器IP端口前缀等的配置
            buildConfigField("String", "ENVIROMENT", "\"pro\"")
        }
        debugTest.initWith(release)
        debugTest {
            // 可调试
            debuggable true
            // LogUtils 是否打印日志
            buildConfigField("boolean", "IS_DEBUGING", "true")
            buildConfigField("String", "ENVIROMENT", "\"test\"")
            // App版本号后缀
            versionNameSuffix ".test"
            // 执行构建这个编译版本时，如果某个子模块中没有 debugTest 这个版本
            // Gradle 3.X 会一一按照你指定的 matchingFallbacks 从前往后依次寻找，直到类型匹配
            matchingFallbacks = ['debugTest', 'release', 'debug']
        }
    }
    
    dependencies {
        // Pandora 调试用
        debugImplementation 'com.github.whataa:pandora:v2.0.0'
        debugTestImplementation 'com.github.whataa:pandora-no-op:v2.0.1'
        // 这里如果想开启Pandora功能的话，启动会黑屏，没有主进程，只有其他进程
        //debugTestImplementation 'com.github.whataa:pandora:v2.0.0'
        releaseImplementation 'com.github.whataa:pandora-no-op:v2.0.1'
    }

**Comment by whataa** [comment]
没有主进程可能是启动就崩溃了，你能把崩溃日志贴一下吗？

我在本地demo上按照你的gradle添加了debugTest的buildTypes，打包安装后没有出现你所描述的问题。

**Comment by Dramadream** [comment]
~~~
2019-04-12 15:01:22.837 13233-13233/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.clickcoo.yishuobaobao, PID: 13233
    java.lang.ExceptionInInitializerError
        at tech.linjiang.pandora.e.a.a(HistoryRecorder.java:72)
        at tech.linjiang.pandora.e.a.onActivityCreated(HistoryRecorder.java:32)
        at android.app.Application.dispatchActivityCreated(Application.java:212)
        at android.app.Activity.onCreate(Activity.java:1045)
        at com.yishuobaobao.activities.LogoActivity.onCreate(LogoActivity.java:148)
        at android.app.Activity.performCreate(Activity.java:7143)
        at android.app.Activity.performCreate(Activity.java:7134)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3033)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:817)
     Caused by: android.database.sqlite.SQLiteException: near ",": syntax error (code 1): , while compiling: CREATE TABLE log_crash, createTime INTEGER, startTime INTEGER, type TEXT, cause TEXT, stack TEXT, versionCode INTEGER, versionName TEXT, sys_sdk TEXT, sys_version TEXT, rom TEXT, cpu TEXT, phone TEXT, locale TEXT)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:921)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:502)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1753)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1682)
        at tech.linjiang.pandora.a.a.onCreate(CacheDatabase.java:47)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:333)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:238)
        at tech.linjiang.pandora.a.a.a(CacheDatabase.java:67)
        at tech.linjiang.pandora.a.a.a(CacheDatabase.java:122)
        at tech.linjiang.pandora.a.d.a(History.java:28)
        at tech.linjiang.pandora.a.d.<clinit>(History.java:15)
        at tech.linjiang.pandora.e.a.a(HistoryRecorder.java:72) 
        at tech.linjiang.pandora.e.a.onActivityCreated(HistoryRecorder.java:32) 
        at android.app.Application.dispatchActivityCreated(Application.java:212) 
        at android.app.Activity.onCreate(Activity.java:1045) 
        at com.yishuobaobao.activities.LogoActivity.onCreate(LogoActivity.java:148) 
        at android.app.Activity.performCreate(Activity.java:7143) 
        at android.app.Activity.performCreate(Activity.java:7134) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3033) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:6811) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:817) 
~~~

**Comment by Dramadream** [comment]
后面还有Bugly收集的这样的报错信息：
~~~
java.lang.NoClassDefFoundError: tech.linjiang.pandora.a.e
        at tech.linjiang.pandora.f.b.a(OkHttpInterceptor.java:88)
        at tech.linjiang.pandora.f.b.a(OkHttpInterceptor.java:50)
        at okhttp3.internal.c.h.a(RealInterceptorChain.java:147)
        at okhttp3.internal.c.h.a(RealInterceptorChain.java:121)
        at okhttp3.ah.h(RealCall.java:200)
        at okhttp3.ah$a.c(RealCall.java:147)
        at okhttp3.internal.b.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ExceptionInInitializerError
        at tech.linjiang.pandora.f.b.a(OkHttpInterceptor.java:88)
        at tech.linjiang.pandora.f.b.a(OkHttpInterceptor.java:50)
        at okhttp3.internal.c.h.a(RealInterceptorChain.java:147)
        at okhttp3.internal.c.h.a(RealInterceptorChain.java:121)
        at okhttp3.ah.h(RealCall.java:200)
        at okhttp3.ah.b(RealCall.java:77)
        at tech.linjiang.pandora.f.a.a.a.c.a(OkHttpURLConnection.java:477)
        at tech.linjiang.pandora.f.a.a.a.c.getResponseCode(OkHttpURLConnection.java:514)
        at com.tencent.bugly.proguard.s.a(BUGLY:118)
        at com.tencent.bugly.proguard.v.run(BUGLY:355)
        at com.tencent.bugly.proguard.au.run(BUGLY:723)
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: android.database.sqlite.SQLiteException: near ",": syntax error (code 1): , while compiling: CREATE TABLE log_crash, createTime INTEGER, startTime INTEGER, type TEXT, cause TEXT, stack TEXT, versionCode INTEGER, versionName TEXT, sys_sdk TEXT, sys_version TEXT, rom TEXT, cpu TEXT, phone TEXT, locale TEXT)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:921)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:502)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1753)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1682)
        at tech.linjiang.pandora.a.a.onCreate(CacheDatabase.java:47)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:333)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:238)
        at tech.linjiang.pandora.a.a.a(CacheDatabase.java:67)
        at tech.linjiang.pandora.a.a.a(CacheDatabase.java:122)
        at tech.linjiang.pandora.a.e.b(Summary.java:82)
        at tech.linjiang.pandora.a.e.<clinit>(Summary.java:21)
        at tech.linjiang.pandora.f.b.a(OkHttpInterceptor.java:88) 
        at tech.linjiang.pandora.f.b.a(OkHttpInterceptor.java:50) 
        at okhttp3.internal.c.h.a(RealInterceptorChain.java:147) 
        at okhttp3.internal.c.h.a(RealInterceptorChain.java:121) 
        at okhttp3.ah.h(RealCall.java:200) 
        at okhttp3.ah.b(RealCall.java:77) 
        at tech.linjiang.pandora.f.a.a.a.c.a(OkHttpURLConnection.java:477) 
        at tech.linjiang.pandora.f.a.a.a.c.getResponseCode(OkHttpURLConnection.java:514) 
        at com.tencent.bugly.proguard.s.a(BUGLY:118) 
        at com.tencent.bugly.proguard.v.run(BUGLY:355) 
        at com.tencent.bugly.proguard.au.run(BUGLY:723) 
        at java.lang.Thread.run(Thread.java:764) 

~~~

**Comment by Dramadream** [comment]
在Release时试图使用Pandora也是一样的黑屏情况。

**Comment by whataa** [comment]
看样子是由于开启了代码混淆导致Pandora在创建自身数据库的时候崩溃的，和buildType没有联系，
你可以添加如下混淆规则来避免：
```
-keep class tech.linjiang.pandora.cache.**{*;}
```

因为Pandora是为开发测试阶段设计的，考虑到混淆开启仅针对正式包，所以没有提供混淆规则

**Comment by Dramadream** [comment]
晕，就知道是应该是挺简单的问题导致的，没想到是混淆。
没有仔细调整debug和release的配置。
感谢作者解疑。
