### ISSUE TITLE
okhttp 新版本已经取消UnrepeatableRequestBody

### ISSUE THREAD

**Issue by xuhaoyang** [whataa/pandora#45]
okhttp 新版本已经取消UnrepeatableRequestBody

**Comment by whataa** [comment]
不是很懂，有什么问题吗？

**Comment by andreag85** [comment]
I'm having this crash too using androidx_v2.0.2.
Here is the full stacktrace

> HttpTask Error : Failed resolution of: Lokhttp3/internal/http/UnrepeatableRequestBody;
    java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/http/UnrepeatableRequestBody;
        at tech.linjiang.pandora.network.okhttp3.internal.huc.OkHttpsURLConnection.<init>(OkHttpsURLConnection.java:31)
        at tech.linjiang.pandora.network.okhttp3.OkUrlFactory.open(OkUrlFactory.java:67)
        at tech.linjiang.pandora.network.okhttp3.OkUrlFactory.open(OkUrlFactory.java:57)
        at tech.linjiang.pandora.network.okhttp3.OkUrlFactory$1.openConnection(OkUrlFactory.java:86)
        at java.net.URL.openConnection(URL.java:992)
        at com.facebook.GraphRequest.createConnection(GraphRequest.java:1422)
        at com.facebook.GraphRequest.toHttpConnection(GraphRequest.java:1082)
        at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:1170)
        at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:1146)
        at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:1130)
        at com.facebook.GraphRequest.executeAndWait(GraphRequest.java:1105)
        at com.facebook.GraphRequest.executeAndWait(GraphRequest.java:999)
        at com.facebook.internal.FetchedAppSettingsManager.getAppSettingsQueryResponse(FetchedAppSettingsManager.java:369)
        at com.facebook.internal.FetchedAppSettingsManager.access$100(FetchedAppSettingsManager.java:62)
        at com.facebook.internal.FetchedAppSettingsManager$1.run(FetchedAppSettingsManager.java:175)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.internal.http.UnrepeatableRequestBody" on path: DexPathList[[zip file "/data/app/XXX-6VmxSEPP9nsq-K39_NBsVA==/base.apk"],nativeLibraryDirectories=[/data/app/XXX-6VmxSEPP9nsq-K39_NBsVA==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at tech.linjiang.pandora.network.okhttp3.internal.huc.OkHttpsURLConnection.<init>(OkHttpsURLConnection.java:31) 
        at tech.linjiang.pandora.network.okhttp3.OkUrlFactory.open(OkUrlFactory.java:67) 
        at tech.linjiang.pandora.network.okhttp3.OkUrlFactory.open(OkUrlFactory.java:57) 
        at tech.linjiang.pandora.network.okhttp3.OkUrlFactory$1.openConnection(OkUrlFactory.java:86) 
        at java.net.URL.openConnection(URL.java:992) 
        at com.facebook.GraphRequest.createConnection(GraphRequest.java:1422) 
        at com.facebook.GraphRequest.toHttpConnection(GraphRequest.java:1082) 
        at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:1170) 
        at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:1146) 
        at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:1130) 
        at com.facebook.GraphRequest.executeAndWait(GraphRequest.java:1105) 
        at com.facebook.GraphRequest.executeAndWait(GraphRequest.java:999) 
        at com.facebook.internal.FetchedAppSettingsManager.getAppSettingsQueryResponse(FetchedAppSettingsManager.java:369) 
        at com.facebook.internal.FetchedAppSettingsManager.access$100(FetchedAppSettingsManager.java:62) 
        at com.facebook.internal.FetchedAppSettingsManager$1.run(FetchedAppSettingsManager.java:175) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by whataa** [comment]
请使用最新版本v2.0.3

Please check the latest v2.0.3

**Comment by whataa** [comment]
#56
