### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by joker-fu** [whataa/pandora#52]
CrashReport: java.lang.NullPointerException: interceptor com.hyhs.oa.framework.network.HttpLoggingInterceptor@5d7b7d returned null
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:157)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at tech.linjiang.pandora.network.OkHttpInterceptor.intercept(OkHttpInterceptor.java:64)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by whataa** [comment]
第二行返回了null，看看是不是 `com.hyhs.oa.framework.network.HttpLoggingInterceptor` 这个类的问题呢？

**Comment by whataa** [comment]
好的，谢谢

**Comment by whataa** [comment]
请使用v2.0.4
