### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by KaelInvoker** [whataa/pandora#53]
按照文档集成到项目中，运行后直接崩溃
`
   java.lang.RuntimeException: Unable to get provider tech.linjiang.pandora.Pandora: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at android.app.ActivityThread.installProvider(ActivityThread.java:5363)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4881)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4815)
        at android.app.ActivityThread.access$1600(ActivityThread.java:168)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5659)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at tech.linjiang.pandora.util.ViewKnife.getResouces(ViewKnife.java:37)
        at tech.linjiang.pandora.util.ViewKnife.getString(ViewKnife.java:53)
        at tech.linjiang.pandora.FuncController$1.getName(FuncController.java:137)
        at tech.linjiang.pandora.FuncController.addFunc(FuncController.java:45)
        at tech.linjiang.pandora.FuncController.addDefaultFunctions(FuncController.java:129)
        at tech.linjiang.pandora.FuncController.<init>(FuncController.java:39)
        at tech.linjiang.pandora.Pandora.init(Pandora.java:39)
        at tech.linjiang.pandora.Pandora.onCreate(Pandora.java:33)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
        at android.support.v4.content.FileProvider.attachInfo(FileProvider.java:382)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5360)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4881) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4815) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:168) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:150) 
        at android.app.ActivityThread.main(ActivityThread.java:5659) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712) `

**Comment by whataa** [comment]
请问这是每次都出现吗，能否提供下你的手机型号、系统版本、app是否是多进程等信息，按照日志来看我觉得不应该发生😢

**Comment by whataa** [comment]
不知道产生原因，但是增加了防护措施，请使用v2.0.4

**Comment by KaelInvoker** [comment]
您好，使用v2.0.4依然报空指针。
![image](https://user-images.githubusercontent.com/37531571/58249504-a72d3b00-7d91-11e9-8d48-8d82d5058849.png)

**Comment by whataa** [comment]
你好，你的项目有使用插件化相关的吗

**Comment by KaelInvoker** [comment]
@whataa 我项目中使用了multidex，会不会和这个有关系

**Comment by whataa** [comment]
我司项目也有用到multidex，但没有出现你这种情况。如果你方便的话，可以创建一份简单的复现demo上传到GitHub吗？

**Comment by KaelInvoker** [comment]
@whataa 您好，如果配置了multidex，需要做额外的配置么？另外，我们项目最低支持5.0，只开启了multidex，并没有配置multiDexKeepProguard，项目编译后我在build目录下没找到build/intermediates/multi-dex/{flavor}/{buildType}/maindexlist.txt这个文件，另外也没有相关的multidex的task。大佬知道怎么回事么

**Comment by KaelInvoker** [comment]
刚刚我打了个断点，发现在Pandora初始化时，调用context.getApplicationContext()竟然是nulll。

**Comment by KaelInvoker** [comment]
图片发不上去，可以的话能给个qq么

**Comment by whataa** [comment]
你好，这应该不是multidex的问题，crash确实是getApplicationContext返回了null，但是我水平有限暂时不知道原因，所以我说如果你方便的话上传一份可以复现的demo上来我分析分析

**Comment by KaelInvoker** [comment]
问题解决了.. 是我们项目自己的问题。大佬，请问项目中引入的话，可以只引debugImplementation 'com.github.whataa:pandora:v${RELEASE}'这一句么？release那个就不写了，不会影响realse吧？

**Comment by whataa** [comment]
如果仅仅是引入了，并没有在项目中添加Pandora相关代码（例如将Pandora.get().getOKHttpInterceptor添加到OKHttp拦截器中），就不用在release中引入no-op模块；反之就需要，不过也不用担心，no-op只有几个空类，不会增大体积或引发方法过多之类。（我很好奇引发这个问题原因是什么，可以分享下吗

**Comment by KaelInvoker** [comment]
@whataa 一个很蠢的错误...经排查，是项目之前的人在Application重写了getApplicationContext()方法，返回的是自己的application实例。大佬，再问个问题，如果项目使用的是httpUrlconection，怎么才能够拦截所有的请求

**Comment by whataa** [comment]
额，尴尬。Pandora已经支持httpUrlconection的所有请求，无需添加额外代码，你可以看看demo里按钮「URLConnection」的点击代码和效果

**Comment by Charlottenpl** [comment]
还有一种情况会引发这种错误，就是应用配置了多进程，导致出现了两个Application
