### ISSUE TITLE
java.io.EOFException

### ISSUE THREAD

**Issue by LeonDevLifeLog** [whataa/pandora#60]
```
2019-06-18 15:45:47.748 3510-17027/com.example.app W/System.err: java.io.EOFException
2019-06-18 15:45:47.749 3510-17027/com.example.app W/System.err:     at okio.RealBufferedSource.require(RealBufferedSource.java:61)
2019-06-18 15:45:47.749 3510-17027/com.example.app W/System.err:     at okio.GzipSource.consumeHeader(GzipSource.java:114)
2019-06-18 15:45:47.749 3510-17027/com.example.app W/System.err:     at okio.GzipSource.read(GzipSource.java:73)
2019-06-18 15:45:47.749 3510-17027/com.example.app W/System.err:     at okio.Buffer.writeAll(Buffer.java:1135)
2019-06-18 15:45:47.749 3510-17027/com.example.app W/System.err:     at okio.RealBufferedSource.readString(RealBufferedSource.java:199)
2019-06-18 15:45:47.749 3510-17027/com.example.app W/System.err:     at tech.linjiang.pandora.network.OkHttpInterceptor.sourceToStrInternal(OkHttpInterceptor.java:313)
2019-06-18 15:45:47.749 3510-17027/com.example.app W/System.err:     at tech.linjiang.pandora.network.OkHttpInterceptor.requestBodyAsStr(OkHttpInterceptor.java:262)
2019-06-18 15:45:47.749 3510-17027/com.example.app W/System.err:     at tech.linjiang.pandora.network.OkHttpInterceptor.insert(OkHttpInterceptor.java:118)
2019-06-18 15:45:47.749 3510-17027/com.example.app W/System.err:     at tech.linjiang.pandora.network.OkHttpInterceptor.intercept(OkHttpInterceptor.java:50)
2019-06-18 15:45:47.749 3510-17027/com.example.app W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-06-18 15:45:47.749 3510-17027/com.example.app W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-06-18 15:45:47.749 3510-17027/com.example.app W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
2019-06-18 15:45:47.749 3510-17027/com.example.app W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
2019-06-18 15:45:47.749 3510-17027/com.example.app W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
2019-06-18 15:45:47.749 3510-17027/com.example.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-06-18 15:45:47.750 3510-17027/com.example.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-06-18 15:45:47.750 3510-17027/com.example.app W/System.err:     at java.lang.Thread.run(Thread.java:784)
```

**Comment by whataa** [comment]
你好，这个看起来是网络连接传输这块的问题，和有没有Pandora应该没关系，可能是数据流还没传输完网络突然中断了。不知道你这边是一直出错还是仅这一次情况？

**Comment by LeonDevLifeLog** [comment]
一直出现

**Comment by whataa** [comment]
方便发一个可测试的api吗，我这边调试下

**Comment by LeonDevLifeLog** [comment]
retrofit,具体不太清楚哪个api产生的,我来调试一下

**Comment by whataa** [comment]
请问有任何新进展吗

**Comment by ywqian** [comment]
pandora和oss上传文件一起使用会报错：
java.io.IOException: read failed: EBADF (Bad file descriptor)
at libcore.io.IoBridge.read(IoBridge.java:478)
at java.io.FileInputStream.read(FileInputStream.java:177)
at okio.Okio$2.read(Okio.java:140)
at com.alibaba.sdk.android.oss.network.ProgressTouchableRequestBody.writeTo(ProgressTouchableRequestBody.java:56)
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
....
